"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
const express_1 = require("express");
const sesion_1 = require("../middleware/sesion");
const food_1 = require("../controllers/food");
const router = (0, express_1.Router)();
exports.router = router;
router.get("/", sesion_1.checkJwt, food_1.getFoods);
router.post("/", sesion_1.checkJwt, food_1.postFood);
router.delete("/:id", sesion_1.checkJwt, food_1.deleteOneFood);
