"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
const express_1 = require("express");
const sesion_1 = require("../middleware/sesion");
const music_1 = require("../controllers/music");
const router = (0, express_1.Router)();
exports.router = router;
router.get("/", sesion_1.checkJwt, music_1.getMusics);
router.post("/", sesion_1.checkJwt, music_1.postMusic);
router.delete("/:id", sesion_1.checkJwt, music_1.deleteOneMusic);
